### ISSUE TITLE
Character Model Bug and Softlocking If Mod Exists on WorldGen

### ISSUE THREAD

**Issue by ridesdragons** [cem3cem3/AppliedEcogisticsIssues#23]
oops, didn't see you had a github, copy-pasting my report here

hey, noticed an issue when adding this mod to a fresh game, and was able to consistently pull off the bug. If you create a world with the mod installed, after logging into the world and completing character creation, in your backpack you'll see that your character isn't equipped with any clothes, except the shirt slot, which has a white square. you cannot enter third person mode, attempting you edit your look causes the game to softlock. attempting to move the white square will crash the game. if you relog, your clothes will reappear, and can enter 3rd person, but you'll have a random look and gender. attempting to edit your character will result in losing the ability to enter third person again, and will softlock when attempting to edit.

I don't know if this is caused by generating a world with the mod already there, or by creating a character in a server with the mod already there. If you create your character before adding the mod into the world, though, you can freely edit your character and enter third person without issue after adding the mod. further testing will need to be done to see if the bug is caused by world gen or by character gen.

EDIT: yeeeeeeeep it's caused on character gen. when first joining a game that has this mod enabled, character generation breaks and you're unable to edit your character without softlocking the game, so everyone who's going to play on a server with this mod will have to hop on _before_ the mod is added in

**Comment by ridesdragons** [comment]
Issue resolved in 1.22.0.9.1.9R

though I do gotta ask, how the hell did a storage mod break character creation....

**Comment by cem3cem3** [comment]
I thought that was an Eco bug for the longest time for the same reason. Turns out Eco will try to modify the clothing items directly when you try to save changes. It was only if this modification succeed, that it would set colors etc. server wide.

I had a bug that caused some modifications to fail if they were single inventories (which is what the clothing slots are). I assume that since this kind of thing was never supposed to fail in vanilla, it could cause soft locks on the client somehow.
